### ISSUE TITLE
sudo apt-get install python3.10-dev also needed for some packages

### ISSUE THREAD

**Issue by rehanhaider** [CloudBytes-Academy/CloudBytes.dev#106]
### Discussed in https://github.com/CloudBytesDotDev/CloudBytes.dev/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **spalfy** February 24, 2022</sup>
Related to: https://cloudbytes.dev/snippets/upgrade-python-to-latest-version-on-ubuntu-linux

Packages that compile C Python modules during installation require an updated python-dev package.
Can be installed with `sudo apt-get install python3.10-dev`

Example error when the above is needed:
```
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/tmp/pip-install-ljjblyio/httptools_182114364e604caa9530ba42c1a43bdc/vendor/llhttp/include -I/tmp/pip-install-ljjblyio/httptools_182114364e604caa9530ba42c1a43bdc/vendor/llhttp/src -I/home/spalfy/vens/backend310/include -I/usr/include/python3.10 -c httptools/parser/parser.c -o build/temp.linux-x86_64-3.10/httptools/parser/parser.o -O2
      httptools/parser/parser.c:20:10: fatal error: Python.h: No such file or directory
         20 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
```</div>

**Comment by hdadhich01** [comment]
I have included it in this [tutorial](https://github.com/hdadhich01/wsl-terminal) and opened #126 to add it at the end along with the tutorial.

**Comment by rehanhaider** [comment]
> I have included it in this [tutorial](https://github.com/hdadhich01/wsl-terminal) 

Is this needed or in scope of the article?

**Comment by hdadhich01** [comment]
Needed; the tutorial just has a subsection that is a condensed list of the commands run in the article.

**Comment by rehanhaider** [comment]
Sounds generic and not relevant.

**Comment by hdadhich01** [comment]
The issue cited above is better explained [here](https://stackoverflow.com/questions/22571848/debugging-the-error-gcc-error-x86-64-linux-gnu-gcc-no-such-file-or-directory) on why it's needed for many dependencies.

**Comment by rehanhaider** [comment]
I understood the part about the issue, but I don't think the tutorial you have referenced is relevant or specific enough to be included.
