### ISSUE TITLE
Why not simply do `sudo cp /usr/bin/python3.10 /usr/bin/python`

### ISSUE THREAD

**Issue by mgoldenbe** [CloudBytes-Academy/CloudBytes.dev#122]
Why not simply do `sudo cp /usr/bin/python3.10 /usr/bin/python` to make python3.10 default?

**Comment by rehanhaider** [comment]
Python is NOT python binary executable alone, you need to have compatible pip, compatible venv, and many other version compatible binaries at the RIGHT path. So you need to change the pointer to the `python` command
